name: Update z5e.m3u

on:
  workflow_dispatch:  # Allows you to click "Run Workflow" manually
  schedule:
    - cron: '*/1 * * * *' # Runs every 5 minutes

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch file from URL
      run: |
        # Downloading the file from your provided link
        curl -L -o z5e.m3u "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/z5.m3u"

    - name: Commit and push changes
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       git config --global user.name "github-actions[bot]"
       git config --global user.email "github-actions[bot]@users.noreply.github.com"

       git add z5e.m3u
       
       # Only commit if the file has actually changed
       if git diff --staged --quiet; then
         echo "No changes detected. Skipping commit."
         exit 0
       fi

       git commit -m "Sync z5e.m3u with source"
       git pull origin main --rebase
       git push origin HEAD:main
